---

- name: install dependencies
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2

- name: install the opencast package repository key
  apt_key:
    url: https://pkg.opencast.org/gpgkeys/opencast-deb.key
    state: present

- name: install the opencast package repository
  apt_repository:
    repo: >
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      stable testing
    filename: opencast
    state: present
