---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: opencast-repository-centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: opencast-repository-centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: opencast-repository-debian
    image: docker.io/pycontribs/debian
    pre_build_image: true
  - name: opencast-repository-ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
